### ISSUE TITLE
Git master build fails

### ISSUE THREAD

**Issue by prokoudine** [OpenMusicKontrollers/mephisto.lv2#1] opened 2019-12-10 13:06 UTC
```
$ meson build
The Meson build system
Version: 0.51.2
Source dir: /home/alex/soft/sound/lv2/mephisto.lv2
Build dir: /home/alex/soft/sound/lv2/mephisto.lv2/build
Build type: native build
Project name: mephisto.lv2
Project version: undefined
C compiler for the host machine: cc (gcc 9.2.1 "cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
Build machine cpu family: x86_64
Build machine cpu: x86_64

meson.build:8:0: ERROR: Subproject directory not found and d2tk.wrap file not found

A full log can be found at /home/alex/soft/sound/lv2/mephisto.lv2/build/meson-logs/meson-log.txt
```

**Comment by ventosus** [comment] 2020-03-29 20:14
Cannot reproduce this, thus closing the issue.

If this should still be the case, feel free to repoen the issue.

**Closed** 2020-04-15 16:58 UTC
